# Configuration for simplified GitHub-focused agent

# LLM Configuration
llm_base_url: "http://localhost:11434"
llm_model: "qwen3:32b"

# GitHub MCP Server Configuration  
github_server:
  enabled: true
  timeout: 90  # MCP initialization timeout in seconds
  
# Timeout Configuration
timeouts:
  mcp_init: 90        # MCP client initialization timeout
  mcp_cleanup: 20     # MCP cleanup timeout
  api_request: 300    # API request timeout for integration tests
  llm_request: 300    # LLM request timeout
  
# Debug Configuration
debug_mode: false
test_mode: false
