# Generated by Copilot
# Ensure the project root is in sys.path so tests can import the 'app' package
import sys
import os

# Project root is the directory containing this conftest.py
project_root = os.path.abspath(os.path.dirname(__file__))
if project_root not in sys.path:
    sys.path.insert(0, project_root)
