services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        COMPONENT: api
        PORT: "5002"
    container_name: aquarius-api-1
    environment:
      - APP_COMPONENT=api
      - PORT=5002
      - LLM_BASE_URL=http://host.docker.internal:11434
      - TEST_MODE=true
      - LLM_MODEL=qwen3:8b
    group_add:
      - "20"
      - "0"
    ports:
      - "5002:5002"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./keys.yaml:/app/keys.yaml:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks: 
      - aquarius_network
    extra_hosts:
      - "host.docker.internal:host-gateway"


  ui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        COMPONENT: ui
        PORT: "7860"
        API_URL: "http://api:5002/api/chat"
    container_name: aquarius-ui-1
    environment:
      - APP_COMPONENT=ui
      - PORT=7860
      - API_URL=http://api:5002/api/chat
      - TEST_MODE=true
    ports:
      - "7860:7860"
    volumes:
      - ./keys.yaml:/app/keys.yaml:ro
      - ./app:/app/app
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks: 
      - aquarius_network

networks:
  aquarius_network:
    driver: bridge
