# Generated by Copilot
# Ensure the project root is in sys.path so tests can import the 'app' package
import sys
import os

# Calculate project root (one level up from tests directory)
project_root = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))
if project_root not in sys.path:
    sys.path.insert(0, project_root)
